version: "3.8"

services:
  web:
    image: nginx:1.23-alpine
    container_name: intern-web
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - intern-dev
    ports:
      - ${EXTERNAL_WEBSERVER_PORT}:${EXTERNAL_WEBSERVER_PORT}
    restart: unless-stopped
    depends_on:
      - php
      - database

  php:
    build:
      context: ./environment/dev/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    container_name: intern-php
    env_file:
      - .env
    working_dir: /application/backend
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
      - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - intern-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  database:
    image: mysql:8.0
    container_name: intern-mysql
    volumes:
      - intern-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DEV_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DEV_DB_DATABASE}
      - MYSQL_USER=${DOCKER_DEV_DB_USERNAME}
      - MYSQL_PASSWORD=${DOCKER_DEV_DB_PASSWORD}
    networks:
      - intern-dev
    ports:
      - ${DOCKER_DEV_DB_EXTERNAL_PORT:-3306}:3306
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: intern-redis
    ports:
      - ${FORWARD_REDIS_PORT:-6379}:6379
    volumes:
      - intern-redis-data:/data
    networks:
      - intern-dev
    restart: unless-stopped
  
  node:
    image: node:18.7.0-alpine3.16
    container_name: intern-node
    env_file:
      - .env
    working_dir: /application/frontend
    tty: true
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    networks:
      - intern-dev
    ports:
      - ${EXTERNAL_NODE_PORT:-5173}:${EXTERNAL_NODE_PORT:-5173}
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: intern-mailhog
    ports:
      - ${MAIL_PORT}:1025
      - ${MAILHOG_DASHBOARD_PORT}:8025
    networks:
      - intern-dev
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome
    container_name: intern-selenium
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - intern-dev
    restart: unless-stopped


networks:
  intern-dev:
    driver: bridge

volumes:
  intern-mysql-data:
    name: intern-mysql-data
  intern-redis-data:
    name: intern-redis-data
