version: "3.8"

services:
  web:
    image: nginx:1.21-alpine
    container_name: intern-web
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./environment/nginx/${MODE}.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${EXTERNAL_WEBSERVER_PORT}:80"

  php:
    build:
      context: ./environment/php
      args:
        XDEBUG_HOST: ${XDEBUG_HOST}
        XDEBUG_PORT: ${XDEBUG_PORT}
        XDEBUG_INSTALL: ${XDEBUG_INSTALL}
        XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}
    container_name: intern-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    restart: unless-stopped
  
  node:
    image: node:16-alpine3.14
    container_name: intern-node
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - "${DEVELOPMENT_NODE_PORT}:8080"
