version: "3.7"

services:
  web:
    image: nginx:1.19-alpine
    container_name: intern-web
    working_dir: /application
    restart: unless-stopped
    tty: true
    volumes:
      - .:/application
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${EXTERNAL_WEBSERVER_PORT}:80"

  php:
    image: ghcr.io/blumilksoftware/php:8.0.7.0
    container_name: intern-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    restart: unless-stopped
