export default {
  SET_COMPANIES: "SET_COMPANIES",
  SET_FILTERS: "SET_FILTERS",
  SET_FACULTIES: "SET_FACULTIES",
  SET_DOCUMENTS: "SET_DOCUMENTS",
  SET_TAGS: "SET_TAGS",
  MANAGE_ACTIVE_TAGS: "MANAGE_ACTIVE_TAGS",
  RESET_ACTIVE_TAGS: "RESET_ACTIVE_TAGS",
  SET_COMPANIES_MERGED: "SET_COMPANIES_MERGED",
};
