name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install and build frontend
        env:
          VUE_APP_MAPBOX_TOKEN: "${{ secrets.VUE_APP_MAPBOX_TOKEN }}"
          VUE_APP_MAPBOX_STYLE_URL: "${{ secrets.VUE_APP_MAPBOX_STYLE_URL }}"

        run: |
          npm install
          npm run-script build

      - name: Install and build backend
        env:
          CURRENT_UID: 1000
          XDEBUG_HOST: 172.17.0.1
          XDEBUG_PORT: 9003
          XDEBUG_INSTALL: true
          XDEBUG_START_WITH_REQUEST: yes
          XDEBUG_MODE: debug
          XDEBUG_LOG_LEVEL: 0

        run: |
          composer install
          echo 'MAPBOX_TOKEN="${{ secrets.VUE_APP_MAPBOX_TOKEN }}"' > .env
          echo 'COMMANDLINE_MODE=deploy' >> .env
          composer intern-populate
          composer intern-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: public
          FOLDER: public
          CLEAN: true
