name: PHP codestyle

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "**.php"
      - "composer.json"
      - "composer.lock"
      - "phpunit.xml"
      - "env.ci"

jobs:
  test-and-lint-php:
    name: PHP codestyle
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --working-dir=./backend

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-dependencies-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-dependencies

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest --working-dir=./backend

      - name: Run PHP linter
        run: composer cs --working-dir=./backend
