name: Check the PR title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check-pr-title:
    name: Check the PR title
    runs-on: ubuntu-20.04
    steps:
      - uses: blumilksoftware/action-pr-title@1.1.0
